### ISSUE TITLE
Support `timestamptz`

### ISSUE THREAD

**Issue by shiroemons** [ridgepole/ridgepole#394]
PostgreSQL's `timestamp with time zone` is supported in Rails(Active Record) v7.0.
From the above correspondence, `timestamptz` have been added.
It would be great if ridgepole would support this.🙏

- refs
  - https://github.com/rails/rails/pull/41084?w=1
  - https://github.com/rails/rails/pull/41395?w=1
  - https://github.com/rails/rails/blob/v7.0.0/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb#L133

**Comment by winebarrel** [comment]
Thank you for your issue 😃 
Supports timestamptz in https://github.com/ridgepole/ridgepole/pull/400.

**Comment by winebarrel** [comment]
v1.2.0 has been released.
