### ISSUE TITLE
If the Index comment is blank, it always output the difference

### ISSUE THREAD

**Issue by VTRyo** [ridgepole/ridgepole#396]
# Description

I was using schemafile to give the Index comments. However, it was blank.

example schemafile
```rb
 create_table "articles", force: :cascade do |t|
      t.bigint :office_id, null: false, unsigned: true
      t.index [:office_id], name: "index_office_id", comment: ''
 end
```

When I applied this, add_index was executed every time.

--dry-run
```
# CREATE INDEX `index_office_id` USING btree ON `articles` ( `office_id`)
# ALTER TABLE hogehoge
# ALTER TABLE hugahuga
```

example execute result.
```
-- add_index("articles", ["office_id"], {:name=>"index_office_id", :comment=>"", :using=>:btree, :unique=>false})
```

I can avoid this result by inserting a string instead of a blank or by removing the comment option.

```rb
 create_table "articles", force: :cascade do |t|
      t.bigint :office_id, null: false, unsigned: true
      t.index [:office_id], name: "index_office_id"
 end
```

## I figured I was missing a test with BLANK, but I'd love your input

Should I test with rspec of comment? If so, is this file appropriate?

https://github.com/ridgepole/ridgepole/blob/a4055cc93f64d39df7218d8cb8417cf8ce747654/spec/mysql/comment/comment_spec.rb

**Comment by winebarrel** [comment]
Please write the following information:

* Ridgepole version
*  Ruby version
* Rails/Active Record version
* MySQL/PostgreSQL version

**Comment by VTRyo** [comment]
Thank you very much.

- Ridgepole `1.1`
- Ruby `3.0.4`
- Rails/ActiveRecord `6.1.6`
- MySQL `5.7.26`

**Comment by winebarrel** [comment]
Thank you for version info.

Empty comments cannot be added due to rails specifications.
cf. https://github.com/rails/rails/blob/v7.0.4/activerecord/lib/active_record/connection_adapters/abstract_mysql_adapter.rb#L380

`comment: ""` must be removed from the DSL.
