### ISSUE TITLE
Support for `create_enum` syntax

### ISSUE THREAD

**Issue by mkusaka** [ridgepole/ridgepole#403]
# Description

First, Thank you for the great gem.

Are there any plans for the ridgepole gem to support the `create_enum` syntax supported in rails 7.0?
ref. https://github.com/rails/rails/pull/41469

I tried with ridgepole1.2.0, but it doesn't seem to be supported at this moment.

There seems to be a [workaround](https://blog.saeloun.com/2022/01/12/rails-7-adds-custom-enum-support-in-postgresql) for this situation, but support would be appreciated.

# Schemafile

```rb
# frozen_string_literal: true

create_enum :status, ["draft", "published", "archived", "trashed"]
```

# DDL

```
CREATE TYPE status AS ENUM ('draft', 'published', 'archived', 'trashed');
```

# Export

```
# -*- mode: ruby -*-
# vi: set ft=ruby :


```

# Apply with `--verbose`

```
Apply `Schemafile` (dry-run)
# Parse DSL
[ERROR] undefined method `create_enum' for #<Ridgepole::DSLParser::Context:0x0000000106bb83a0 @__working_dir="/path/to/project/dir", @__definition={}, @__execute=[]>
Did you mean?  create_table
        Schemafile:3:in `eval'
```

**Comment by winebarrel** [comment]
v1.2.1 has been released.
https://rubygems.org/gems/ridgepole/versions/1.2.1

Please try it out.

**Comment by qriouchida** [comment]
@winebarrel 

I apologize for commenting even though this issue has been closed.

Thank you for providing such a wonderful gem.

Regarding the updates in version 1.2.1, could you confirm if my understanding is correct?

- Added support for the t.enum syntax.
- The actual Enum needs to be set up separately, perhaps in SQL, before its usage.
  - For instance, executing CREATE TYPE status AS ENUM ('draft', 'published', 'archived', 'trashed'); prior to running the ridgepole command.

I appreciate your confirmation on this.

**Comment by winebarrel** [comment]
> Regarding the updates in version 1.2.1, could you confirm if my understanding is correct?

Yes. Your understanding is right.
