### ISSUE TITLE
If option is specified for timestamp, option is applied only to created_at column.

### ISSUE THREAD

**Issue by ayatk** [ridgepole/ridgepole#427]
# Description

- Middleware versions
  - Ridgepole 1.2.0
  - Ruby 3.2.1
  - Rails/Active Record 7.0.6
  - MySQL 8.0.33

If you migrate using the following Gemfile and Schemafile, you will get the following Export Schema

```ruby
source 'https://rubygems.org'

gem 'mysql2'
gem 'ridgepole'
```
```ruby
create_table 'examples', force: :cascade  do |t|
  t.timestamps index: true
end
```

```
$ bundle exec ridgepole -c config.yml --apply                                                                                    
Apply `Schemafile`
-- create_table("examples")
   -> 0.0107s
-- add_index("examples", ["created_at"])
   -> 0.0116s
$ bundle exec ridgepole -c config.yml --export
# Export Schema
create_table "examples", charset: "utf8mb4", collation: "utf8mb4_0900_ai_ci", force: :cascade do |t|
  t.datetime "created_at", null: false
  t.datetime "updated_at", null: false
  t.index ["created_at"], name: "index_examples_on_created_at"
end
```

However, the schema I want is as follows, and the updated_at index is not created in the results that are actually applied.

```ruby
create_table "examples", charset: "utf8mb4", collation: "utf8mb4_0900_ai_ci", force: :cascade do |t|
  t.datetime "created_at", null: false
  t.datetime "updated_at", null: false
  t.index ["created_at"], name: "index_examples_on_created_at"
  t.index ["updated_at"], name: "index_examples_on_updated_at"
end
```

The options passed to `TableDefinition#column` are probably passed by reference, so if you pass the same option to multiple `TableDefinition#column`, you need to do a deep copy like `Object#deep_dup` in ActiveSupport.

**Comment by winebarrel** [comment]
v1.2.1 has been released.
https://rubygems.org/gems/ridgepole/versions/1.2.1

Please try it out.

**Comment by ayatk** [comment]
I just updated to v1.2.1 and confirmed that it's fixed! thank you!
