### ISSUE TITLE
'renamed_from column option for new table' is not working AR 7.1

### ISSUE THREAD

**Issue by uekkee** [ridgepole/ridgepole#452]
Hello.

I found a problem when running ridgepole v2.0 with ActiveRecord 7.1.

I get an error when setting **renamed_from column option for a new table** .

I wrote a spec that reproduces the problem.
https://github.com/ridgepole/ridgepole/pull/451

Thank you for your help.

**Comment by winebarrel** [comment]
[v2.0.1](https://rubygems.org/gems/ridgepole/versions/2.0.1) has been released.
