### ISSUE TITLE
Always bigint id changes operations after upgrading from MySQL 5.7 to MySQL 8.0

### ISSUE THREAD

**Issue by Tsubasa08** [ridgepole/ridgepole#455]
# Description
- Ridgepole：2.0.1
- Ruby：3.2.1
- Rails：7.0.4.2
- MySQL：8.0.32

Since upgrading from MySQL 5.7 to MySQL 8.0, I've been encountering an issue where executing `apply` consistently triggers `change_column` operations, even when no changes are made to the schema. This behavior was not observed prior to the upgrade.

https://dev.mysql.com/doc/refman/8.0/en/numeric-type-attributes.html
> MySQL supports an extension for optionally specifying the display width of integer data types in parentheses following the base keyword for the type. For example, [INT(4)](https://dev.mysql.com/doc/refman/8.0/en/integer-types.html) specifies an [INT](https://dev.mysql.com/doc/refman/8.0/en/integer-types.html) with a display width of four digits. This optional display width may be used by applications to display integer values having a width less than the width specified for the column by left-padding them with spaces. (That is, this width is present in the metadata returned with result sets. Whether it is used is up to the application.)

It appears that these changes in MySQL 8.0's handling of integer data types' display width might be causing Ridgepole to misinterpret the schema, leading to unnecessary `change_column` operations. Has anyone else encountered this issue, or can provide insight into this behavior?

# Schemafile
```
create_table "posts", id: { type: :bigint, unsigned: true }, charset: "utf8mb4", force: :cascade do |t|
  t.string   "name", limit: 100, null: false
  t.boolean  "is_deleted", null: false
  t.datetime "created_at", null: false, precision: nil
  t.datetime "updated_at", null: false, precision: nil
end
```

### mysql5.7
```sql
mysql> show columns from posts;
+------------+---------------------+------+-----+---------+----------------+
| Field      | Type                | Null | Key | Default | Extra          |
+------------+---------------------+------+-----+---------+----------------+
| id         | bigint(20) unsigned | NO   | PRI | NULL    | auto_increment |
| name       | varchar(100)        | NO   |     | NULL    |                |
| is_deleted | tinyint(1)          | NO   |     | NULL    |                |
| created_at | datetime            | NO   |     | NULL    |                |
| updated_at | datetime            | NO   |     | NULL    |                |
+------------+---------------------+------+-----+---------+----------------+
```

### mysql8
```sql
mysql> show columns from posts;
+------------+-----------------+------+-----+---------+----------------+
| Field      | Type            | Null | Key | Default | Extra          |
+------------+-----------------+------+-----+---------+----------------+
| id         | bigint unsigned | NO   | PRI | NULL    | auto_increment |
| name       | varchar(100)    | NO   |     | NULL    |                |
| is_deleted | tinyint(1)      | NO   |     | NULL    |                |
| created_at | datetime        | NO   |     | NULL    |                |
| updated_at | datetime        | NO   |     | NULL    |                |
+------------+-----------------+------+-----+---------+----------------+
```

# Apply with `--verbose`
```
bundle exec ridgepole --env development --config config/database.yml --allow-pk-change --apply --file db/schemas/Schemafile  --verbose
Apply `db/schemas/Schemafile`
# Parse DSL
# Load tables
#   posts
# Compare definitions
#   posts
    "name"=>{:options=>{:limit=>100, :null=>false}, :type=>:string},
    "updated_at"=>
     {:options=>{:null=>false, :precision=>nil}, :type=>:datetime}},
- :options=>
-  {:charset=>"utf8mb4",
-   :collation=>"utf8mb4_general_ci",
-   :id=>{:type=>:bigint, :unsigned=>true}}}
+ :options=>{:charset=>"utf8mb4", :id=>{:type=>:bigint, :unsigned=>true}}}
# Update schema
-- change_column("posts", :id, :bigint, {:unsigned=>true, :auto_increment=>true, :comment=>nil})
   -> 0.0797s
```

**Comment by Tsubasa08** [comment]
@winebarrel 
アサインありがとうございます！
改めて過去のissueも確認したのですが、似たような事象のissueが見当たらずでして、こちらご確認頂いてもよろしいでしょうか？

**Comment by winebarrel** [comment]
型の横の数字はMySQL表示幅の問題で、特にパースには関係はないです、
Schemafileのテーブルの定義を以下のように変更してください

```ruby
create_table "posts", id: { type: :bigint, unsigned: true }, charset: "utf8mb4", collation: "utf8mb4_general_ci", force: :cascade do |t|
# ...
end
```

**Comment by Tsubasa08** [comment]
@winebarrel 
ご確認ありがとうございます！
ご指摘のとおり、`collation: "utf8mb4_general_ci"`を追記したところ`No change`となりました。ありがとうございしました。
```
bundle exec ridgepole --env development --config config/database.yml --allow-pk-change --apply --file db/schemas/Schemafile
Apply `db/schemas/Schemafile`
No change
```

> デフォルトの照合順が変わった影響ではないでしょうか？
そのようですね。
